feat: add lib/minion.lib.sh and mksh to bin, refactor Makefile

diff --git a/bin/mkjs b/bin/mkjs
--- a/bin/mkjs
+++ b/bin/mkjs
@@ -6,43 +6,44 @@ set -eu
 # License: MIT
 # Description: A Bash script that creates a JS template file.
 
-error (){
-    printf "%s\n" "ERROR ${2:-1}" >&2
-    printf "%s\n" "$1" >&2
-    exit "${2:-1}"
-}
+SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+MINION_PATH="${SCRIPT_DIR}/lib/minion.lib.sh"
+INCLUDE_LIST=("error" "check_dep" "check_perm" "get_last")
 
-var_check (){
-    if [ ! -v "$1" ] || [ -z "${!1}" ]; then
-        error "Variable \"$1\" is not set." 2
-    fi
-}
-
-conf_dir="$(dirname "$0")/config"
-conf_file="${conf_dir}/mkjs.conf"
-
-if [ ! -f "$conf_file" ]; then
-    error "Config \"${conf_file}\" not found." 1
+if [ ! -e "$MINION_PATH" ] || [ -d "$MINION_PATH" ] || [ ! -r "$MINION_PATH" ]; then
+    printf "%s\n" "FATAL 1" >&2
+    printf "%s\n" "\"$(basename "$MINION_PATH")\" not found." >&2
+    exit 1
 fi
 
 # shellcheck source=/dev/null
-source "$conf_file"
+source "$MINION_PATH"
 
-var_arr=(
-    "DATE" "AUTHOR" "LICENSE" "DESCRIPTION"
-    "TEMPLATE_CLASS" "TEMPLATE_FETCH_API" "TEMPLATE_DISPATCH_EVENT" "TEMPLATE_EVENT_LISTENER" "TEMPLATE_VITEST_TEST"
-)
-
-for var in "${var_arr[@]}"; do
-    var_check "$var"
-done
-
-if [ $# -lt 1 ]; then
-    error "Usage: mkjs [FILENAME(S)]" 3
+if [ "$(type -t "check_func")" != "function" ] || ! check_func "${INCLUDE_LIST[@]}"; then
+    printf "%s\n" "FATAL 2" >&2
+    printf "%s\n" "\"$(basename "$MINION_PATH")\" is incomplete." >&2
+    exit 1
 fi
 
-tmp=$(mktemp)
-trap 'rm -f "$tmp"' EXIT
+CONFIG_FILE="${SCRIPT_DIR}/config/mkjs.conf"
+source_file "$CONFIG_FILE" || error "Config \"$(get_last)\" not found." 1
+
+PARAMETERS=("DATE" "AUTHOR" "LICENSE" "DESCRIPTION"
+    "TEMPLATE_CLASS" "TEMPLATE_FETCH_API" "TEMPLATE_DISPATCH_EVENT" "TEMPLATE_EVENT_LISTENER"
+    "TEMPLATE_VITEST_TEST"
+)
+check_var "${PARAMETERS[@]}" || error "Parameter \"$(get_last)\" is not set." 2
+
+[ "$#" -ge 1 ] || error "Usage: ${0} [FILENAME(S)]" 3
+
+check_content "$@" || error "Empty file name in parameters." 4
+check_absent "$@" || error "\"$(get_last)\" already exists." 5
+check_path "$@" || error  "Directory \"$(get_last)\" not found." 6
+check_path_perm "wx" "$@" || error "Missing write/execute permission for \"$(get_last)\"." 7
+
+init_namespace
+trap del_namespace EXIT
+tmp=$(mktmp_file)
 : > "$tmp"
 
 cat << END >> "$tmp"
@@ -132,26 +133,11 @@ dispatchCustomEvent('EVENT_PLACEHOLDER');
 END
 
 while [ "$#" -gt 0 ]; do
-
-    if [ -z "$1" ]; then
-        error "Empty file name." 4
-    elif [ -e "$1" ]; then
-        error "\"${1}\" already exists." 5
+    if check_absent "$1"; then
+        cp "$tmp" "$1"
+    else
+        warning "Skipped duplicate parameter \"$(get_last)\"."
     fi
-
-    file="$1"
-    dir="$(dirname "$1")"
-
-    if [ ! -d "$dir" ]; then
-        error "Directory \"${dir}\" not found." 6
-    elif [ ! -w "$dir" ]; then
-        error "Missing write permission for \"${dir}\"." 7
-    elif [ ! -x "$dir" ]; then
-        error "Missing execute permission for \"${dir}\"." 8
-    fi
-
-    cp "$tmp" "$file"
-
     shift
 done
 
diff --git a/bin/stripdir b/bin/stripdir
--- a/bin/stripdir
+++ b/bin/stripdir
@@ -6,71 +6,65 @@ set -eu
 # License: MIT
 # Description: A Bash script that strips all EXIF ​​data from files in a directory and its subdirectories.
 
-error (){
-    printf "%s\n" "ERROR ${2:-1}" >&2
-    printf "%s\n" "$1" >&2
-    exit "${2:-1}"
-}
+SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+MINION_PATH="${SCRIPT_DIR}/lib/minion.lib.sh"
+INCLUDE_LIST=("error" "warning" "info" "check_dep"
+    "check_empty" "check_dir" "check_perm" "check_size"
+    "get_last" "init_namespace" "del_namespace" "mktmp_file"
+)
 
-warning (){
-    printf "%s\n" "WARNING" >&2
-    printf "%s\n" "$1" >&2
-}
-
-info (){
-    printf "%s\n" "INFO" >&2
-    printf "%s\n" "$1" >&2
-}
-
-check_dependency (){
-    if ! command -v "$1" >/dev/null 2>&1; then
-        error "Command \"${1}\" not found." 1
-    fi
-}
-
-dependencies=("exiftool")
-
-for dependency in "${dependencies[@]}"; do
-    check_dependency "$dependency"
-done
-
-if [ "$#" -lt 1 ]; then
-    error "Usage: stripdir [DIRNAME(S)]" 2
+if [ ! -e "$MINION_PATH" ] || [ -d "$MINION_PATH" ] || [ ! -r "$MINION_PATH" ]; then
+    printf "%s\n" "FATAL 1" >&2
+    printf "%s\n" "\"$(basename "$MINION_PATH")\" not found." >&2
+    exit 1
 fi
 
-results=$(mktemp)
-trap 'rm -f "$results"' EXIT
+# shellcheck source=/dev/null
+source "$MINION_PATH"
 
-error_counter="0"
+if [ "$(type -t "check_func")" != "function" ] || ! check_func "${INCLUDE_LIST[@]}"; then
+    printf "%s\n" "FATAL 2" >&2
+    printf "%s\n" "\"$(basename "$MINION_PATH")\" is incomplete." >&2
+    exit 1
+fi
+
+DEPENDENCIES=("exiftool")
+check_dep "${DEPENDENCIES[@]}" || error "Command \"$(get_last)\" not found." 1
+
+[ "$#" -ge 1 ] || error "Usage: ${0} [DIRNAME(S)]" 2
+
+check_empty "$@" && error "Empty directory name in parameters." 3
+check_dir "$@" || error "Directory \"$(get_last)\" not found." 4
+check_perm "rwx" "$@" || error "Missing read/write/execute permission for directory \"$(get_last)\"." 5
+
+init_namespace
+trap del_namespace EXIT
+results=$(mktmp_file)
+
+skip_counter="0"
 while [ "$#" -gt 0 ]; do
 
-    if [ ! -e "$1" ]; then
-        error "Directory \"${1}\" not found." 3
-    elif [ ! -d "$1" ]; then
-        error "\"${1}\" is not a directory." 4
-    fi
-
     dir="$1"
-
     : > "$results"
 
     find "$dir" -type f 2>/dev/null > "$results"
+    skip_counter=$(( skip_counter += $(find "$dir" -type f 2>&1 >/dev/null | wc -l) ))
 
-    if [ ! -s "$results" ]; then
-        warning "Directory \"${dir}\" has nothing to strip."
-    else
+    if check_size "$dir"; then
         while IFS= read -r file; do
-            exiftool -all= -overwrite_original "$file" 2>/dev/null >&2 || error_counter=$((error_counter + 1))
+            exiftool -all= -overwrite_original "$file" >/dev/null 2>&1 || skip_counter=$((skip_counter += 1))
         done <"$results"
+    else
+        warning "Directory \"$(get_last)\" is empty."
     fi
 
     shift
 done
 
-if [ "$error_counter" -eq 1 ]; then
-    info "${error_counter} file was not stripped due to unsupported format."
-elif [ "$error_counter" -gt 1 ]; then
-    info "${error_counter} files were not stripped due to unsupported format."
+if [ "$skip_counter" -eq 1 ]; then
+    info "${skip_counter} file/subdirectory was not stripped due to its format/permissions."
+elif [ "$skip_counter" -gt 1 ]; then
+    info "${skip_counter} files/subdirectories were not stripped due to their format/permissions."
 fi
 
 exit 0
